# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a5cb6985184495b3b47edca29463d1d78571e3ba8f4803ff219f84aa721e929d7a1c9bbdea8ae1d9f6526615ba6af6487d1ce4a01cedd554c774fa4c79a5c49

test:
  secret_key_base: 33578244dfcf17f3b1da9045adbdc007f87aa2b4811f58c2f2c7ec926aec9ce25f9f7bdd12c81965ad572a673164d5b19355c4929c6aa88e3e6926e57e77cedb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
